lsi: false
safe: true
source: [https://github.com/andrija-s/schess]
url: https://andrija-s.github.io
baseurl: /schess
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge