tab_spaces = 2
fn_args_layout = "Compressed"
fn_call_width = 120
chain_width = 120
max_width = 140
#control_brace_style = "AlwaysNextLine"
#fn_single_line = true
#imports_indent = "Visual"
#indent_style = "Visual"
#where_single_line = true